export const AppPageConstant = {
  LOGIN: "Login",
  REGISTER: "Register",
  DASHBOARD: "Dashboard",
  LEGAL: "Legal",
  PRIVACY_POLICY: "Privacy Policy",
  ABOUT: "About",
  CONTACT: "Contact",
  SERVICE: "Service",
  SERVICE_AREA: "Service Area",
  FAQ: "FAQ",
  TASK: "Task",
  PROFILE: "Profile",
  USER: "User",
  CUSTOMER: "Customer",
  TASKER: "Tasker",
  STATISTIC: "Statistic",
  AVAILABILITY: "Availability",
  TASKLION_ACCOUNT: "Tasklion Account",
  MANAGE_ACCOUNT: "Manage Account",
  CHANGE_PASSWORD: "Change Password",
  BOOKING: "Booking",
}
