export const AppPageConstant = {
  LOGIN: "Login",
  REGISTER: "Register",
  DASHBOARD: "Dashboard",
  LEGAL: "Legal",
  PRIVACY_POLICY: "Privacy Policy",
  ABOUT: "About",
  CONTACT: "Contact",
  SERVICE: "Service",
  FAQ: "FAQ",
  TASK: "Task",
  PROFILE: "Profile",
  USER: "User",
  STATISTIC: "Statistic",
}
