export const RouteConstant = {
  ROOT: "",
  LOGIN: "login",
  REGISTER: "register",
  DASHBOARD: "dashboard",
  ABOUT: "about",
  CONTACT: "contact",
  SERVICE: "service",
  LEGAL: "legal",
  PRIVACY_POLICY: "privacy-policy",
  FAQ: "faq",
  PROFILE: "profile",
  TASK: "task",
  USER: "user",
  STATISTIC: "statistic",
}
