CREATE TABLE address
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street      VARCHAR(255),
    city        VARCHAR(255),
    state       VARCHAR(255),
    postal_code VARCHAR(255),
    CONSTRAINT pk_address PRIMARY KEY (id)
);