CREATE TABLE maker_checker
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    maker_id           VARCHAR(255),
    checker_id         VARCHAR(255),
    current_value      JSONB,
    new_value          JSONB,
    status             VARCHAR(255),
    creation_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_maker_checker PRIMARY KEY (id)
);