CREATE TABLE personal_detail
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name           VARCHAR(255),
    phone_number        VARCHAR(255),
    date_of_birth       date,
    profile_picture_url VARCHAR(255),
    CONSTRAINT pk_personal_detail PRIMARY KEY (id)
);