CREATE TABLE service_review
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating            DOUBLE PRECISION,
    comment           VARCHAR(255),
    review_date       date,
    reviewer_id       UUID,
    task_id           BIGINT,
    tasker_service_id BIGINT,
    CONSTRAINT pk_service_review PRIMARY KEY (id)
);

ALTER TABLE service_review
    ADD CONSTRAINT uc_e4354ffe1295e19d061f3d78c UNIQUE (reviewer_id, task_id);

ALTER TABLE service_review
    ADD CONSTRAINT FK_SERVICE_REVIEW_ON_REVIEWER FOREIGN KEY (reviewer_id) REFERENCES customer (id);

ALTER TABLE service_review
    ADD CONSTRAINT FK_SERVICE_REVIEW_ON_TASK FOREIGN KEY (task_id) REFERENCES task (id);

ALTER TABLE service_review
    ADD CONSTRAINT FK_SERVICE_REVIEW_ON_TASKER_SERVICE FOREIGN KEY (tasker_service_id) REFERENCES tasker_service (id);