CREATE TABLE service_category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_service_category PRIMARY KEY (id)
);

ALTER TABLE service_category
    ADD CONSTRAINT uc_service_category_name UNIQUE (name);