CREATE TABLE tasker_time_availability
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tasker_id  UUID                                    NOT NULL,
    start_time time WITHOUT TIME ZONE                  NOT NULL,
    end_time   time WITHOUT TIME ZONE                  NOT NULL,
    CONSTRAINT pk_tasker_time_availability PRIMARY KEY (id)
);

ALTER TABLE tasker_time_availability
    ADD CONSTRAINT FK_TASKER_TIME_AVAILABILITY_ON_TASKER FOREIGN KEY (tasker_id) REFERENCES tasker (id);