CREATE TABLE task
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id        UUID,
    tasker_service_id  BIGINT,
    date               date                                    NOT NULL,
    start_time         time WITHOUT TIME ZONE                  NOT NULL,
    end_time           time WITHOUT TIME ZONE                  NOT NULL,
    service_area_id    BIGINT,
    status             VARCHAR(30),
    remarks            VARCHAR(255),
    creation_date_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_SERVICE_AREA FOREIGN KEY (service_area_id) REFERENCES service_area (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_TASKER_SERVICE FOREIGN KEY (tasker_service_id) REFERENCES tasker_service (id);