CREATE TABLE tasker_service
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tasker_id           UUID,
    description         VARCHAR(255),
    service_category_id BIGINT,
    CONSTRAINT pk_tasker_service PRIMARY KEY (id)
);

ALTER TABLE tasker_service
    ADD CONSTRAINT uc_0d642fbd34d644bef31d10807 UNIQUE (tasker_id, service_category_id);

ALTER TABLE tasker_service
    ADD CONSTRAINT FK_TASKER_SERVICE_ON_SERVICE_CATEGORY FOREIGN KEY (service_category_id) REFERENCES service_category (id);

ALTER TABLE tasker_service
    ADD CONSTRAINT FK_TASKER_SERVICE_ON_TASKER FOREIGN KEY (tasker_id) REFERENCES tasker (id);