CREATE TABLE token
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token               VARCHAR(512),
    token_type          VARCHAR(10),
    expired             BOOLEAN,
    revoked             BOOLEAN,
    tasklion_account_id VARCHAR(255),
    CONSTRAINT pk_token PRIMARY KEY (id)
);

ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_TASKLION_ACCOUNT FOREIGN KEY (tasklion_account_id) REFERENCES tasklion_account (id);