CREATE TABLE user_role
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tasklion_account_id VARCHAR(255),
    role_id             BIGINT,
    CONSTRAINT pk_user_role PRIMARY KEY (id)
);

ALTER TABLE user_role
    ADD CONSTRAINT uc_1b4dc09cfcfa5d1694c34ff5b UNIQUE (tasklion_account_id, role_id);

ALTER TABLE user_role
    ADD CONSTRAINT FK_USER_ROLE_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);

ALTER TABLE user_role
    ADD CONSTRAINT FK_USER_ROLE_ON_TASKLION_ACCOUNT FOREIGN KEY (tasklion_account_id) REFERENCES tasklion_account (id);