-- Get the IDs of all state
WITH state_ids AS (
    SELECT id, name FROM state
)

-- Insert city for each state
INSERT INTO city (name, state_id)
VALUES
-- Johor city
('Johor Bahru', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Tebrau', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Pasir Gudang', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Bukit Indah', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Skudai', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Kluang', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Batu Pahat', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Muar', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Ulu Tiram', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Senai', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Segamat', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Kulai', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Kota Tinggi', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Pontian Kechil', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Tangkak', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Bukit Bakri', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Yong Peng', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Pekan Nenas', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Labis', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Mersing', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Simpang Renggam', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Parit Raja', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Kelapa Sawit', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Buloh Kasap', (SELECT id FROM state_ids WHERE name = 'Johor')),
('Chaah', (SELECT id FROM state_ids WHERE name = 'Johor')),

-- Kedah city
('Sungai Petani', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Alor Setar', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Kulim', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Jitra / Kubang Pasu', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Baling', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Pendang', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Langkawi', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Yan', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Sik', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Kuala Nerang', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Pokok Sena', (SELECT id FROM state_ids WHERE name = 'Kedah')),
('Bandar Baharu', (SELECT id FROM state_ids WHERE name = 'Kedah')),

-- Kelantan city
('Kota Bharu', (SELECT id FROM state_ids WHERE name = 'Kelantan')),
('Pangkal Kalong', (SELECT id FROM state_ids WHERE name = 'Kelantan')),
('Tanah Merah', (SELECT id FROM state_ids WHERE name = 'Kelantan')),
('Peringat', (SELECT id FROM state_ids WHERE name = 'Kelantan')),
('Wakaf Baru', (SELECT id FROM state_ids WHERE name = 'Kelantan')),
('Kadok', (SELECT id FROM state_ids WHERE name = 'Kelantan')),
('Pasir Mas', (SELECT id FROM state_ids WHERE name = 'Kelantan')),
('Gua Musang', (SELECT id FROM state_ids WHERE name = 'Kelantan')),
('Kuala Krai', (SELECT id FROM state_ids WHERE name = 'Kelantan')),
('Tumpat', (SELECT id FROM state_ids WHERE name = 'Kelantan')),

-- Melaka city
('Bandaraya Melaka', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Bukit Baru', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Ayer Keroh', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Klebang', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Masjid Tanah', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Sungai Udang', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Batu Berendam', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Alor Gajah', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Bukit Rambai', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Ayer Molek', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Bemban', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Kuala Sungai Baru', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Pulau Sebang', (SELECT id FROM state_ids WHERE name = 'Melaka')),
('Jasin', (SELECT id FROM state_ids WHERE name = 'Melaka')),

-- Negeri Sembilan city
('Seremban', (SELECT id FROM state_ids WHERE name = 'Negeri Sembilan')),
('Port Dickson', (SELECT id FROM state_ids WHERE name = 'Negeri Sembilan')),
('Nilai', (SELECT id FROM state_ids WHERE name = 'Negeri Sembilan')),
('Bahau', (SELECT id FROM state_ids WHERE name = 'Negeri Sembilan')),
('Tampin', (SELECT id FROM state_ids WHERE name = 'Negeri Sembilan')),
('Kuala Pilah', (SELECT id FROM state_ids WHERE name = 'Negeri Sembilan')),

-- Pahang city
('Kuantan', (SELECT id FROM state_ids WHERE name = 'Pahang')),
('Temerloh', (SELECT id FROM state_ids WHERE name = 'Pahang')),
('Bentong', (SELECT id FROM state_ids WHERE name = 'Pahang')),
('Mentakab', (SELECT id FROM state_ids WHERE name = 'Pahang')),
('Raub', (SELECT id FROM state_ids WHERE name = 'Pahang')),
('Jerantut', (SELECT id FROM state_ids WHERE name = 'Pahang')),
('Pekan', (SELECT id FROM state_ids WHERE name = 'Pahang')),
('Kuala Lipis', (SELECT id FROM state_ids WHERE name = 'Pahang')),
('Bandar Jengka', (SELECT id FROM state_ids WHERE name = 'Pahang')),
('Bukit Tinggi', (SELECT id FROM state_ids WHERE name = 'Pahang')),

-- Perak city
('Ipoh', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Taiping', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Sitiawan', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Simpang Empat', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Teluk Intan', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Batu Gajah', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Lumut', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Kampung Koh', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Kuala Kangsar', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Sungai Siput Utara', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Tapah', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Bidor', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Parit Buntar', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Ayer Tawar', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Bagan Serai', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Tanjung Malim', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Lawan Kuda Baharu', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Pantai Remis', (SELECT id FROM state_ids WHERE name = 'Perak')),
('Kampar', (SELECT id FROM state_ids WHERE name = 'Perak')),

-- Perlis city
('Kangar', (SELECT id FROM state_ids WHERE name = 'Perlis')),
('Kuala Perlis', (SELECT id FROM state_ids WHERE name = 'Perlis')),

-- Pulau Pinang city
('Bukit Mertajam', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Georgetown', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Sungai Ara', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Gelugor', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Ayer Itam', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Butterworth', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Perai', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Nibong Tebal', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Permatang Kucing', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Tanjung Tokong', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Kepala Batas', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Tanjung Bungah', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),
('Juru', (SELECT id FROM state_ids WHERE name = 'Pulau Pinang')),

-- Sabah city
('Kota Kinabalu', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Sandakan', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Tawau', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Lahad Datu', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Keningau', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Putatan', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Donggongon', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Semporna', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Kudat', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Kunak', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Papar', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Ranau', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Beaufort', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Kinarut', (SELECT id FROM state_ids WHERE name = 'Sabah')),
('Kota Belud', (SELECT id FROM state_ids WHERE name = 'Sabah')),

-- Sarawak city
('Kuching', (SELECT id FROM state_ids WHERE name = 'Sarawak')),
('Miri', (SELECT id FROM state_ids WHERE name = 'Sarawak')),
('Sibu', (SELECT id FROM state_ids WHERE name = 'Sarawak')),
('Bintulu', (SELECT id FROM state_ids WHERE name = 'Sarawak')),
('Limbang', (SELECT id FROM state_ids WHERE name = 'Sarawak')),
('Sarikei', (SELECT id FROM state_ids WHERE name = 'Sarawak')),
('Sri Aman', (SELECT id FROM state_ids WHERE name = 'Sarawak')),
('Kapit', (SELECT id FROM state_ids WHERE name = 'Sarawak')),
('Batu Delapan Bazaar', (SELECT id FROM state_ids WHERE name = 'Sarawak')),
('Kota Samarahan', (SELECT id FROM state_ids WHERE name = 'Sarawak')),

-- Selangor city
('Subang Jaya', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Klang', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Ampang Jaya', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Shah Alam', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Petaling Jaya', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Cheras', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Kajang', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Selayang Baru', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Rawang', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Taman Greenwood', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Semenyih', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Banting', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Balakong', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Gombak Setia', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Kuala Selangor', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Serendah', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Bukit Beruntung', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Pengkalan Kundang', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Jenjarom', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Sungai Besar', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Batu Arang', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Tanjung Sepat', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Kuang', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Kuala Kubu Baharu', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Batang Berjuntai', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Bandar Baru Salak Tinggi', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Sekinchan', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Sabak', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Tanjung Karang', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Beranang', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Sungai Pelek', (SELECT id FROM state_ids WHERE name = 'Selangor')),
('Sepang', (SELECT id FROM state_ids WHERE name = 'Selangor')),

-- Terengganu city
('Kuala Terengganu', (SELECT id FROM state_ids WHERE name = 'Terengganu')),
('Chukai', (SELECT id FROM state_ids WHERE name = 'Terengganu')),
('Dungun', (SELECT id FROM state_ids WHERE name = 'Terengganu')),
('Kerteh', (SELECT id FROM state_ids WHERE name = 'Terengganu')),
('Kuala Berang', (SELECT id FROM state_ids WHERE name = 'Terengganu')),
('Marang', (SELECT id FROM state_ids WHERE name = 'Terengganu')),
('Paka', (SELECT id FROM state_ids WHERE name = 'Terengganu')),
('Jerteh', (SELECT id FROM state_ids WHERE name = 'Terengganu')),

-- Wilayah Persekutuan city
('Kuala Lumpur', (SELECT id FROM state_ids WHERE name = 'Wilayah Persekutuan')),
('Labuan', (SELECT id FROM state_ids WHERE name = 'Wilayah Persekutuan')),
('Putrajaya', (SELECT id FROM state_ids WHERE name = 'Wilayah Persekutuan'));
